version: '3'

services:
  backstage:
    image: node:16
    command: "sh -c 'yarn install && yarn dev'"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: &postgres_password backstagedev
    ports:
      - "3000:3000"
      - "7007:7007"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: *postgres_password
