version: '3'

services:
  backstage:
    image: node:16
    command: |
      sh -c ' \
        apt-get update \
        && apt-get install -y python3 python3-pip \
        && pip3 install mkdocs-techdocs-core \
        && yarn install \
        && yarn dev \
      '
    working_dir: /app
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: &postgres_password backstagedev
    ports:
      - "3000:3000"
      - "7007:7007"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: *postgres_password
